stages:
  - pull_changes

variables:
  GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"

pull_changes_production_server:
  stage: pull_changes
  tags:
    - production
  only:
    - production

  before_script:
    - mkdir -p ~/.ssh
    - echo "LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFB
      QUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJsd0FBQUFkemMyZ3RjbgpOaEFBQUFB
      d0VBQVFBQUFZRUFzSXRyMlViSVl0NW1CT3NVTjNHeHJrN1RsMHBhZXpuV2tndU02S2htV3ZLVWpO
      ekw0MlRKClZHNjNKY1ZYUG5YNnAyLzNyN1B1bkE5ZWZDbGEyUTd4dVNxK0NUdi81aHVvQ3V6Rk5x
      aXZubWE4amtKRmdZRTBxYXhjM0YKUVdyK201ZEJoeXFldGM5LzlqTmdldDdJSW9sWDM0UzZwRGhS
      VSt1WnYrWU1EczVsWEUyQ2lGZXduQXR0QTNEK0tvVTd5YQpxUHpkdDZIdEZoVzV5MDN5WFA5QjlP
      RjJUVDBDZ1hzVEM1ZlZPWHJTQWZNTy9xeHFSYzFGb3YxVVE4bUtJMzNiTXFSWmVJCklBT2hwejgv
      WTVZT3htZ29SamRHUW9leHc4ZWlOMXY0MlBwa284QWZjeXJRTVBpWDVON25JU0xma0UxTE5Pc1pZ
      a2JrMG8KNnpaekUyRzR0U0gxcTRTRFhCWm11R0ZMLzNrV3hXSnZVdFhqK0c3QWR6QkoyN0RLeWdh
      RDI2VVlBaEUrcEh4ejdINHJEMApXaEVHc2trTVdPd3FPaUI1aUVPMVJkdms0RlRpK3dLc1Zza0x6
      TjRoblZBQzYvQ0dyTE1KODgxUTVnWGlZYVhkOWE2dngrCndWckphRVFuOFBZdFNWMHNlQzhyWXJz
      N1Q1dUpha2plUkxkWXBDU3RBQUFGbUliaXV3V0c0cnNGQUFBQUIzTnphQzF5YzIKRUFBQUdCQUxD
      TGE5bEd5R0xlWmdUckZEZHhzYTVPMDVkS1duczUxcElMak9pb1pscnlsSXpjeStOa3lWUnV0eVhG
      Vno1MQorcWR2OTYrejdwd1BYbndwV3RrTzhia3F2Z2s3LytZYnFBcnN4VGFvcjU1bXZJNUNSWUdC
      Tkttc1hOeFVGcS9wdVhRWWNxCm5yWFBmL1l6WUhyZXlDS0pWOStFdXFRNFVWUHJtYi9tREE3T1pW
      eE5nb2hYc0p3TGJRTncvaXFGTzhtcWo4M2JlaDdSWVYKdWN0Tjhsei9RZlRoZGswOUFvRjdFd3VY
      MVRsNjBnSHpEdjZzYWtYTlJhTDlWRVBKaWlOOTJ6S2tXWGlDQURvYWMvUDJPVwpEc1pvS0VZM1Jr
      S0hzY1BIb2pkYitOajZaS1BBSDNNcTBERDRsK1RlNXlFaTM1Qk5TelRyR1dKRzVOS09zMmN4Tmh1
      TFVoCjlhdUVnMXdXWnJoaFMvOTVGc1ZpYjFMVjQvaHV3SGN3U2R1d3lzb0dnOXVsR0FJUlBxUjhj
      K3grS3c5Rm9SQnJKSkRGanMKS2pvZ2VZaER0VVhiNU9CVTR2c0NyRmJKQzh6ZUlaMVFBdXZ3aHF5
      ekNmUE5VT1lGNG1HbDNmV3VyOGZzRmF5V2hFSi9EMgpMVWxkTEhndksySzdPMCtiaVdwSTNrUzNX
      S1FrclFBQUFBTUJBQUVBQUFHQUU4MEhZeDYvd2VzTXlUZHVsSXRoY05ueGZICkgvOVBzM09Ea29i
      RDNiQVE5ZEh2Rnl3c1hlbU9RMEVYM3hPNVd5Nzgyc201M1VRTmV1Y3NHV3FXcTJMTjBBNUh0QXg5
      ZkoKUUxSdXFDTkNVME5WbWFVUU02YkF0OWtYcnpTVk9OUy9rcWhkVC9hUWZsWThFK2JIbUpPK3Bv
      bXk3QldrTGd5RWRQL3NoNApDTDhZZWtKTlJpcURxZlRVSE1NekZxVEw0R0lMYi96U1ZSdUp6bU1r
      bkRTYS90ZjJBOFN3eHhPQUdNVU13T1E3eWxTa2V2CklseEhMUjRKVmU4UTRPdDlYVjZ6bytHVU5L
      NFlTNGtENWRxalMvWi9XSnc5YW15dzRuOCsvVFkzbktPcmFMNFdLTjljUksKa0JTdzY0c0NUSG1K
      OGtjc0cvNzI5TnJLdmJuUkUxVEQwV20rd3FZMzUvMmxHdmlZWVpvTWFlQ3cyUFlYd3F2RjEveEVp
      OApFNFhuR2lYTjY4TkRjN1c0TWNhZDhmcGpGY0FSVWZBeEszRUpOcEJJcEdzcGFIVUQ4Y0Uvc0Qx
      VHNiaU1SbGFoUzA1MDNaCjNDNDV3L2Y2OFFUYXU2TTJERWVubnArSmFDT1lYUnlRV0xoTDgxY0Zq
      NzUvSmUvUW1FaGtyVGF1aXZHOU0yM01zQkFBQUEKd1FETnpnSGNhQlNCeWRDV1pkMWVUczhsWmcz
      NVNhZG8xNitwT2RkakZvYnloNTd3c3k5K2drZlVwUE8ya0NYYkxhT1QwUQp5bDkxZHp5ZGpOMU96
      ZEVpdUxIUEdKQmxGejVIWmZHaUlZVm1UWGVTa3l2NkszQlFoQ05yUFh2b25zb0ZJb0JhVm9EQ2Qw
      Ck1rdzI1UkxGNUFtdjdBL3NOaFlhb1dEMHNkWHVqL2o1WGMwazRXajhPQzVWeGtkZ3NCcFR4dkR6
      ZURWN0l4MXhLamJFOGgKZXpJNDU1Q2lVWmRrdWFYNHpzdTdJRWlOd3JZRXRpcWdWR0RqM3dVYzZ6
      aXJPbmp4c0FBQURCQU54NUcvRE5zNmtSOWU0cwpUYXpJZUtINmFLamFnTkI5SDY2NWVJRVRHMUNu
      OExvM2VNYXdYWWxETVNnckMwL05WQU9kajFvVFFVMmwxeUtLUHh4MWU2CjdHYkJ2TktxeHBOUlNs
      RmcwT3E0emx5bWlwcnhTSjFhMUg0L2pFMVJtSGc5NytydlJPKy9TZGdWYnRHZHhFSzY5VG1CLzUK
      WTZoYU41Y1Bob2JWMERFeGhzZ2I4UTZSeXk3cTJqWXRHTndTemErMjd2djlZMTR6ZUY2a3NhOTE1
      aFViTWNzVlE3YlFtSwpYQ2FiWGNZTFVUd3I4b253TDhTMEhpcndncGFhSWtMUUFBQU1FQXpQNHdH
      RlVySUthM1duUU1VUER5eEVHSmxSVERTNjFTCmxsUmloeEVNRUZnOGxaOW11eE01Uk51dEk3UVpN
      TXB1cWxDaVYycDRJMTUzdXlwd3NERW1aMm1VVmIvbTVMd29SL1cwcTkKMHFIenU2V1hyYllkdDVh
      a1Z4MXpoclZjN3h1UUlzYTMzQ0RUS3FWTWFjeEJNWW9oMVg5OTU3ZHJ5VlZ4REtMR3o4WVduVQpz
      QUpNMjA4N1BLQ3FqYWFlL09PT2h4c0QvNXJtM1Y1MFZRSWVnZXhvN0tQK1JKMVl2SDltVTQySy96
      RlBoR2hsdDNXQ2pRCnB6djg3MmJyWllMOUtCQUFBQUcyMTFiR2x6WVVCdGRXeHBjMkV0VEdGMGFY
      UjFaR1V0TnpReU1BRUNBd1FGQmdjPQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H "75.119.153.212" >> ~/.ssh/known_hosts

  script:
    - |
      git_pull() {
        dir=$1
        echo "Marking $dir as safe directory for Git"
        git config --global --add safe.directory $dir

        echo "Pulling changes for $dir"
        cd $dir
        git add .  # Add all changes
        git commit -m "Runner Committing local changes before pull" || echo "No changes to commit"  # Commit changes if any
        git pull git@gitlab.com:development3123049/tibaasiliweb.git
      }

      # Call the function for each directory
      git_pull /var/www/tibaasili/tibaasiliweb/


  after_script:
    # jjkkk
